name: Deploy Service

on:
    push:
        branches:
            - developer

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.13
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "measuresoft"
                  heroku_email: "180105604@aluno.unb.br"
